export const memoryFeatures = [
  "Yes",
  "No",
  "UFS 4.2",
  "UFS 4.1",
  "UFS 4.0",
  "UFS 3.1",
  "UFS 3.0",
  "UFS 2.2",
  "UFS 2.1",
  "UFS 2.0",
  "eMMC 5.1",
  "eMMC 5.0",
  "NVMe",
  "3D NAND",
  "LPDDR5X",
  "LPDDR5",
  "LPDDR4X",
  "LPDDR4",
  "Dual Storage Variant",
  "Expandable Storage",
  "Dedicated microSD Slot",
  "No microSD slot",
  "microSDXC",
  "microSDHC",
  "External SSD Support",
  "OTG Storage Support",
  "Adoptable Storage",
  "Format as Internal Storage",
  "TRIM support",
  "UHS-I Support",
  "UHS-II Support",
  "A2-rated",
  "U3",
  "V30",
  "V60",
  "V90",
  "High-Speed Storage",
  "UFS + eMMC combo",
  "Shared storage with SIM",
  "UFS",
]
export const displayFeatures = [
  "HDR10",
  "HDR10+",
  "60Hz Refresh Rate",
  "90Hz Refresh Rate",
  "120Hz Refresh Rate",
  "144Hz Refresh Rate",
  "165Hz Refresh Rate",
  "240Hz Touch Sampling Rate",
  "360Hz Touch Sampling Rate",
  "720Hz Touch Sampling Rate",
  "Always-on Display",
  "Dolby Vision",
  "HLG",
  "Ambient Display",
  "LTPO Technology",
  "DC Dimming",
  "High Brightness Mode",
  "Sunlight Display",
  "True Tone",
  "Wide Color Gamut",
  "DCI-P3 Color Space",
  "10-bit Color",
  "12-bit Color",
  "Adaptive Refresh Rate",
  "Eye Comfort Mode",
  "Low Blue Light",
  "Flicker-free",
  "Auto Brightness",
  "In-display Fingerprint Sensor",
  "Under-display Camera",
  "HDR Video Playback",
  "DisplayMate A+ Certification",
]

export const RAM_TYPES = [
  "SRAM",
  "DRAM",
  "SDRAM",
  "DDR",
  "DDR2",
  "DDR3",
  "DDR4",
  "DDR5",
  "LPDDR3",
  "LPDDR4",
  "LPDDR4X",
  "LPDDR5",
  "LPDDR5X",
]
export const batteryFeatures = [
  "Charging",
  "Fast Charging",
  "Super Fast Charging",
  "Ultra Fast Charging",
  "Quick Charge",
  "USB Power Delivery",
  "Wireless Charging",
  "Fast Wireless Charging",
  "Reverse Wireless Charging",
  "Reverse Charging",
  "Bypass Charging",
  "Battery Health Monitoring",
  "Smart Charging",
  "Adaptive Charging",
  "Overcharge Protection",
  "Temperature Control",
  "Battery Saver Mode",
  "Ultra Power Saving Mode",
  "AI Power Management",
  "Dual Cell Battery",
  "Graphene Battery",
  "Silicon-Carbon Battery",
  "Removable Battery",
  "Non-removable Battery",
]

export const bodyCertifications = [
  "IP52",
  "IP53",
  "IP54",
  "IP55",
  "IP57",
  "IP58",
  "IP64",
  "IP65",
  "IP66",
  "IP67",
  "IP68",
  "IP69",
  "IP69K",
  "MIL-STD-810G",
  "MIL-STD-810H",
  "CE Certification",
  "FCC Certification",
  "RoHS Compliant",
  "SAR Certified",
  "TÜV Rheinland Certified",
  "SGS Certified",
  "UL Certified",
  "Energy Star Certified",
]
export const bodyBuilds = [
  "Glass front",
  "Glass back",
  "Plastic front",
  "Plastic back",
  "Plastic frame",
  "Aluminum frame",
  "Aluminum back",
  "Stainless steel frame",
  "Titanium frame",
  "Ceramic back",
  "Ceramic body",
  "Metal frame",
  "Metal body",
  "Leather back",
  "Eco leather back",
  "Vegan leather back",
  "Silicone polymer back",
  "Rubberized back",
  "Carbon fiber back",
  "Gorilla Glass front",
  "Gorilla Glass back",
  "Victus Glass front",
  "Victus Glass back",
]

export const simSlotOptions = [
  "No SIM slot",
  "Single SIM",
  "eSIM Only",
  "Dual SIM",
  "Dual SIM (Dual Standby)",
  "Dual SIM (Dual Active)",
  "Dual SIM + eSIM",
  "Triple SIM",
  "Quad SIM",
]

export const simTypeOptions = [
  "Mini-SIM",
  "Micro-SIM",
  "Nano-SIM",
  "eSIM",
  "Nano-SIM + Nano-SIM",
  "Nano-SIM + eSIM",
  "Dual Nano-SIM",
  "Dual Nano-SIM + eSIM",
  "Nano-SIM + eSIM + eSIM",
  "eSIM Only",
  "Nano-SIM + Micro-SIM",
  "Micro-SIM + Micro-SIM",
  "Dual Micro-SIM",
  "Hybrid Dual SIM",
  "Dual SIM (Nano-SIM, dual stand-by)",
]

export const networkTechnologyOptions = [
  "GSM",
  "CDMA",
  "TD-SCDMA",
  "HSPA",
  "HSPA+",
  "EVDO",
  "LTE",
  "LTE-A",
  "LTE-A Pro",
  "5G",
  "5G SA",
  "5G NSA",
  "5G mmWave",
  "5G Sub-6GHz",
  "6G",
]

export const phonePositioningOptions = [
  "GPS",
  "GLONASS",
  "BDS",
  "Galileo",
  "QZSS",
]

export const cameraFeatures = [
  "PDAF",
  "Laser AF",
  "OIS",
  "EIS",
  "HDR",
  "Panorama",
  "Night Mode",
  "Portrait Mode",
  "Dual LED Flash",
  "Dual Pixel PDAF",
  "Depth Sensor",
  "LED Flash",
]

export const phoneSensors = [
  "Face Unlock",
  "Accelerometer",
  "Gyroscope",
  "Proximity",
  "Compass",
  "Magnetometer",
  "Barometer",
  "Ambient Light Sensor",
  "Color Spectrum Sensor",
  "Hall Sensor",
  "Thermometer",
  "Heart Rate Sensor",
  "SpO2 Sensor",
  "UWB (Ultra Wideband)",
]

export const specialFeatures = [
  "AI Assistant",
  "AI Features",
  "Game Mode",
  "Gaming Triggers",
  "Cooling System",
  "Liquid Cooling",
  "Vapor Chamber Cooling",
  "Stereo Speakers",
  "Dolby Atmos",
  "Hi-Res Audio",
  "3.5mm Headphone Jack",
  "FM Radio",
  "Infrared Blaster",
  "Satellite Communication",
  "Emergency SOS via Satellite",
  "Ultra Wideband (UWB)",
  "Desktop Mode",
  "Multi-window",
  "Split Screen",
  "Screen Recording",
  "Always-on Display",
  "Edge Display",
  "Stylus Support",
  "S Pen Support",
  "Knock Gesture",
  "Air Gestures",
  "Water Resistance",
  "Dust Resistance",
  "Rugged Design",
  "Secure Folder",
  "Face Recognition",
]

export const soundFeatures = [
  "Stereo Speakers",
  "Dolby Atmos",
  "Hi-Res Audio",
  "Noise Cancellation",
  "Dual Microphones",
]

export const EXTRA_FIELD_SUGGESTIONS = {
  os: [
    { key: "upgrades", label: "Upgrades" },
    { key: "kernel", label: "Kernel" },
    { key: "software_update", label: "Software Update" },
    { key: "security_patch", label: "Security Patch" },
    { key: "android_version", label: "Android Version" },
    { key: "ui_version", label: "UI Version" },
    { key: "bootloader", label: "Bootloader Status" },
    { key: "root_support", label: "Root Support" },
    { key: "os_optimizations", label: "OS Optimizations" },
  ],

  platform: [
    { key: "process_node", label: "Process Node (nm)" },
    { key: "architecture", label: "Architecture" },
    { key: "ai_engine", label: "AI Engine / NPU" },
    { key: "cpu_cores", label: "CPU Cores" },
    { key: "cpu_frequency", label: "CPU Frequency" },
    { key: "gpu_frequency", label: "GPU Frequency" },
    { key: "benchmark_score", label: "Benchmark Score (Antutu/Geekbench)" },
    { key: "thermal_management", label: "Thermal Management" },
  ],

  memory: [
    { key: "ufs_version", label: "UFS Version" },
    { key: "read_speed", label: "Read Speed" },
    { key: "write_speed", label: "Write Speed" },
    { key: "expandable_storage_type", label: "Expandable Storage Type" },
    { key: "max_storage_support", label: "Max Storage Support" },
  ],

  display: [
    { key: "touch_sampling_rate", label: "Touch Sampling Rate" },
    { key: "hdr_support", label: "HDR Support" },
    { key: "hdr_type", label: "HDR Type (HDR10+, Dolby Vision)" },
    { key: "color_gamut", label: "Color Gamut" },
    { key: "contrast_ratio", label: "Contrast Ratio" },
    { key: "screen_to_body_ratio", label: "Screen-to-Body Ratio" },
    { key: "peak_brightness", label: "Peak Brightness" },
    { key: "panel_manufacturer", label: "Panel Manufacturer" },
    { key: "dc_dimming", label: "DC Dimming" },
    { key: "always_on_display", label: "Always-On Display" },
  ],

  battery: [
    { key: "charging", label: "Charging" },
    { key: "wireless_charging", label: "Wireless Charging" },
    { key: "reverse_charging", label: "Reverse Charging" },
    { key: "charging_time", label: "Charging Time" },
    { key: "battery_life", label: "Battery Life (Usage)" },
    { key: "fast_charging_standard", label: "Fast Charging Standard" },
    { key: "battery_health_features", label: "Battery Health Features" },
    { key: "removable", label: "Removable Battery" },
  ],

  network: [
    { key: "2g", label: "2G" },
    { key: "3g", label: "3G" },
    { key: "4g", label: "4G" },
    { key: "5g", label: "5G" },
    { key: "6g", label: "6G" },
    { key: "lte_bands", label: "LTE Bands" },
    { key: "carrier_aggregation", label: "Carrier Aggregation" },
    { key: "volte", label: "VoLTE Support" },
    { key: "vo_wifi", label: "VoWiFi Support" },
    { key: "network_latency", label: "Network Latency" },
    { key: "dual_5g", label: "Dual 5G Standby" },
    {
      key: "n/a",
      label: "2G, 3G, 4G not supported.",
    },
  ],

  connectivity: [
    { key: "wifi_version", label: "WiFi Version" },
    { key: "wifi_features", label: "WiFi Features (Dual-band, Hotspot)" },
    { key: "bluetooth_version", label: "Bluetooth Version" },
    { key: "bluetooth_features", label: "Bluetooth Features (A2DP, LE)" },
    { key: "infrared", label: "Infrared (IR Blaster)" },
    { key: "usb_features", label: "USB Features (OTG, Type-C)" },
    { key: "ultra_wideband", label: "Ultra Wideband (UWB)" },
  ],

  body: [
    { key: "water_resistance", label: "Water Resistance" },
    { key: "dust_resistance", label: "Dust Resistance" },
    { key: "ip_rating", label: "IP Rating" },
    { key: "materials", label: "Build Materials" },
    { key: "frame_material", label: "Frame Material" },
    { key: "back_material", label: "Back Material" },
    { key: "ergonomics", label: "Ergonomics / Grip" },
  ],

  sound: [
    { key: "audio_quality", label: "Audio Quality" },
    { key: "dolby_support", label: "Dolby Atmos Support" },
    { key: "hi_res_audio", label: "Hi-Res Audio" },
    { key: "speaker_type", label: "Speaker Type (Stereo/Mono)" },
    { key: "microphone", label: "Microphone Quality / Count" },
  ],

  features: [
    { key: "face_unlock", label: "Face Unlock" },
    { key: "fingerprint_type", label: "Fingerprint Type" },
    { key: "gaming_mode", label: "Gaming Mode" },
    { key: "cooling_system", label: "Cooling System" },
    { key: "haptics", label: "Haptic Feedback" },
    { key: "smart_features", label: "Smart Features (AI, Gestures)" },
    { key: "security_features", label: "Security Features" },
  ],

  camera: [
    { key: "sensor_brand", label: "Sensor Brand (Sony, Samsung)" },
    { key: "ois", label: "OIS (Optical Image Stabilization)" },
    { key: "eis", label: "EIS (Electronic Stabilization)" },
    { key: "hdr_photo", label: "HDR Photo Support" },
    { key: "night_mode", label: "Night Mode" },
    { key: "portrait_mode", label: "Portrait Mode" },
    { key: "video_features", label: "Video Features (4K, 8K, HDR)" },
    { key: "slow_motion", label: "Slow Motion" },
  ],
} as const

export const CPU_CORE_OPTIONS = [
  { label: "Single-core", value: "single-core" },
  { label: "Dual-core", value: "dual-core" },
  { label: "Triple-core", value: "triple-core" },
  { label: "Quad-core", value: "quad-core" },
  { label: "Hexa-core", value: "hexa-core" },
  { label: "Seven-core", value: "seven-core" },
  { label: "Octa-core", value: "octa-core" },
  { label: "Deca-core", value: "deca-core" },
]
export const getExtraFieldLabel = (
  name: keyof typeof EXTRA_FIELD_SUGGESTIONS
) => {
  const field = EXTRA_FIELD_SUGGESTIONS[name]
  if (!field) {
    return []
  }
  return field.map((f) => f.label)
}
